# Backup & Restore — 备份恢复工具
# 自动化备份和一键恢复功能

**版本**: 1.0

---

## 功能概述

提供自动备份、手动备份和一键恢复功能，确保记忆数据安全。

---

## 工具脚本

### backup.py — 备份工具

```python
#!/usr/bin/env python3
"""AI Memory System 备份工具"""

import shutil
import json
from datetime import datetime
from pathlib import Path

def backup(memory_dir: str, backup_dir: str = None) -> str:
    """
    执行备份
    
    Args:
        memory_dir: 记忆库目录
        backup_dir: 备份存储目录（默认: memory-bank/backups/）
    
    Returns:
        备份文件路径
    """
    memory_path = Path(memory_dir)
    
    # 生成备份文件名
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_name = f"backup_{timestamp}"
    
    # 默认备份目录
    if backup_dir is None:
        backup_dir = memory_path.parent / "backups"
    
    backup_path = Path(backup_dir) / backup_name
    backup_path.mkdir(parents=True, exist_ok=True)
    
    # 复制文件（排除加密文件）
    exclude_patterns = ["encrypted.json", "*.pyc", "__pycache__"]
    
    for item in memory_path.iterdir():
        if item.name in exclude_patterns:
            continue
        if item.is_dir():
            shutil.copytree(item, backup_path / item.name, dirs_exist_ok=True)
        else:
            shutil.copy2(item, backup_path / item.name)
    
    # 保存备份元数据
    metadata = {
        "timestamp": timestamp,
        "source": str(memory_path),
        "files": [f.name for f in backup_path.rglob("*") if f.is_file()]
    }
    
    with open(backup_path / "backup_meta.json", "w") as f:
        json.dump(metadata, f, indent=2)
    
    return str(backup_path)
```

### restore.py — 恢复工具

```python
#!/usr/bin/env python3
"""AI Memory System 恢复工具"""

import shutil
import json
from pathlib import Path

def restore(backup_path: str, target_dir: str, confirm: bool = True) -> bool:
    """
    从备份恢复
    
    Args:
        backup_path: 备份目录路径
        target_dir: 目标恢复目录
        confirm: 是否需要确认（默认 True）
    
    Returns:
        是否恢复成功
    """
    backup_path = Path(backup_path)
    target_path = Path(target_dir)
    
    if not backup_path.exists():
        raise FileNotFoundError(f"备份不存在: {backup_path}")
    
    # 读取备份元数据
    meta_file = backup_path / "backup_meta.json"
    if meta_file.exists():
        with open(meta_file) as f:
            metadata = json.load(f)
        print(f"备份时间: {metadata['timestamp']}")
        print(f"文件数量: {len(metadata['files'])}")
    
    if confirm:
        response = input(f"确认恢复到 {target_dir}? (yes/no): ")
        if response.lower() != "yes":
            print("恢复已取消")
            return False
    
    # 执行恢复
    if target_path.exists():
        # 备份当前数据
        current_backup = target_path.parent / "pre_restore_backup"
        shutil.copytree(target_path, current_backup, dirs_exist_ok=True)
        print(f"当前数据已备份到: {current_backup}")
    
    # 复制备份文件
    for item in backup_path.iterdir():
        if item.name == "backup_meta.json":
            continue
        dest = target_path / item.name
        if item.is_dir():
            if dest.exists():
                shutil.rmtree(dest)
            shutil.copytree(item, dest)
        else:
            shutil.copy2(item, dest)
    
    print(f"恢复成功！")
    return True

def list_backups(backup_dir: str) -> list[dict]:
    """列出所有备份"""
    backup_path = Path(backup_dir)
    if not backup_path.exists():
        return []
    
    backups = []
    for folder in sorted(backup_path.iterdir(), reverse=True):
        if folder.is_dir():
            meta_file = folder / "backup_meta.json"
            if meta_file.exists():
                with open(meta_file) as f:
                    meta = json.load(f)
                    backups.append({
                        "name": folder.name,
                        "timestamp": meta["timestamp"],
                        "files": len(meta["files"])
                    })
    return backups
```

---

## 使用方式

### 命令行操作

```bash
# 执行备份
python engine/backup.py --source ./memory-bank

# 列出备份
python engine/restore.py --list

# 恢复指定备份
python engine/restore.py --restore backup_20260317_143022

# 恢复到指定目录
python engine/restore.py --restore backup_20260317_143022 --target ./memory-bank
```

### 自动备份配置

```python
# 建议设置定时任务（如每天自动备份）

# Windows 任务计划程序
schtasks /create /tn "AI Memory Backup" /tr "python backup.py" /sc daily /st 02:00

# 或使用 crontab (Linux/Mac)
# 0 2 * * * cd /path/to/ai-memory-system && python engine/backup.py
```

---

## 备份策略建议

| 频率 | 保留数量 | 用途 |
|------|----------|------|
| 每日 | 7 份 | 短期恢复 |
| 每周 | 4 份 | 长期保留 |
| 每月 | 12 份 | 年度归档 |

---

## 注意事项

1. **加密文件** - `encrypted.json` 不会自动备份，需手动保存密码短语
2. **排除文件** - `.git`, `__pycache__`, `*.pyc` 不会备份
3. **恢复前备份** - 恢复前会自动备份当前数据到 `pre_restore_backup`

---

*AI Memory System v1.1 | Generated by WorkBuddy | 2026-03-17*
