# Deduplicator — 自动去重模块
# 检测相似内容，避免重复记忆

**版本**: 1.0

---

## 功能概述

自动去重机制通过计算文本相似度，检测并处理重复或高度相似的记忆内容。

---

## 模块接口

```python
class Deduplicator:
    def __init__(self, similarity_threshold: float = 0.85) -> None
    # 初始化，similarity_threshold 为相似度阈值 (0-1)

    def find_duplicates(self, new_content: str, existing_contents: list[str]) -> list[dict]
    # 检测重复内容，返回相似条目列表

    def is_duplicate(self, content: str, existing_contents: list[str]) -> bool
    # 快速判断是否为重复内容

    def merge_similar(self, entries: list[dict]) -> dict
    # 合并相似条目，保留最新/最完整的内容

    def suggest_action(self, content: str, existing_contents: list[str]) -> str
    # 建议操作："save" | "merge" | "skip"
```

---

## 相似度算法

支持多种相似度计算方式：

1. **余弦相似度** (默认) - 基于 TF-IDF 向量
2. **编辑距离** - 基于字符操作次数
3. **Jaccard 相似度** - 基于词集合交集

```python
# 配置示例
dedup = Deduplicator(
    similarity_threshold=0.85,  # 85%以上相似视为重复
    method="cosine"             # 使用余弦相似度
)
```

---

## 使用方式

### 保存记忆前检测

```python
from core.deduplicator import Deduplicator

dedup = Deduplicator(similarity_threshold=0.85)

# 假设已有记忆
existing = [
    {"id": "mem_001", "content": "用户喜欢简洁的代码风格"},
    {"id": "mem_002", "content": "用户的API密钥是 sk-xxx"},
]

# 检测重复
new_content = "我喜欢简洁的代码风格"
duplicates = dedup.find_duplicates(new_content, [e["content"] for e in existing])

if duplicates:
    # 发现重复，询问用户
    print(f"发现相似记忆: {duplicates}")
    # 建议操作
    action = dedup.suggest_action(new_content, [e["content"] for e in existing])
    print(f"建议操作: {action}")
else:
    # 无重复，可以保存
    ltm.save(content=new_content, ...)
```

### 自动处理策略

| 相似度 | 建议操作 |
|--------|----------|
| ≥ 95% | skip（完全重复，不保存）|
| 85-95% | merge（合并内容）|
| < 85% | save（正常保存）|

---

## 触发时机

推荐在以下时机触发去重检测：

1. **保存记忆时** - `ltm.save()` 前检测
2. **批量导入时** - `kb.import_text()` 前检测
3. **定时任务** - 定期扫描现有记忆

---

*AI Memory System v1.1 | Generated by WorkBuddy | 2026-03-17*
