# Vector Store — 向量检索模块
# 支持语义搜索，补充关键词检索

**版本**: 1.0
**依赖**: chromadb, sentence-transformers

---

## 功能概述

向量检索模块提供语义搜索能力，基于文本 embedding 相似度进行检索。

---

## 模块接口

```python
class VectorStore:
    def __init__(self, persist_dir: Path) -> None
    # 初始化，persist_dir 用于持久化存储

    def add(self, entry_id: str, content: str, metadata: dict = None) -> bool
    # 添加向量到索引

    def search(self, query: str, top_k: int = 5, filter: dict = None) -> list[dict]
    # 语义搜索，返回最相似的 top_k 条

    def delete(self, entry_id: str) -> bool
    # 删除指定向量

    def update(self, entry_id: str, content: str, metadata: dict = None) -> bool
    # 更新向量

    def get_count(self) -> int
    # 返回向量总数
```

---

## 使用方式

### 1. 安装依赖

```bash
pip install chromadb sentence-transformers
```

### 2. API 调用

```python
from core.vector_store import VectorStore

# 初始化
vs = VectorStore(Path("memory-bank/vector_store"))

# 添加记忆时同时添加向量
vs.add(entry_id="mem_001", content="用户喜欢简洁的代码风格", metadata={"category": "preference"})

# 语义搜索
results = vs.search("代码风格偏好", top_k=3)
# 返回: [{"entry_id": "mem_001", "score": 0.92, "content": "..."}]
```

---

## 混合检索策略

推荐使用 **关键词 + 向量混合检索**：

```python
def hybrid_search(query: str, top_k: int = 5):
    # 1. 关键词搜索
    keyword_results = ltm.search(query, limit=top_k * 2)
    
    # 2. 向量搜索
    vector_results = vs.search(query, top_k=top_k * 2)
    
    # 3. 合并并按相关性排序
    combined = merge_results(keyword_results, vector_results)
    
    return combined[:top_k]
```

---

## 配置选项

| 选项 | 默认值 | 说明 |
|------|--------|------|
| `embedding_model` | "sentence-transformers/all-MiniLM-L6-v2" | embedding 模型 |
| `top_k` | 5 | 返回结果数 |
| `similarity_threshold` | 0.7 | 相似度阈值 |

---

*AI Memory System v1.1 | Generated by WorkBuddy | 2026-03-17*
