# Memory Weight — 记忆权重系统
# 支持对记忆的重要性评分，影响检索排序

**版本**: 1.0

---

## 功能概述

记忆权重系统允许用户为每条记忆设置重要性评分，检索时自动按权重排序，确保重要记忆优先呈现。

---

## 权重等级

| 权重值 | 等级名称 | 说明 | 典型场景 |
|--------|----------|------|----------|
| 1 | 低 | 可有可无的信息 | 闲聊内容 |
| 2 | 中 | 一般信息 | 常规项目信息 |
| 3 | 高 | 重要信息 | 用户偏好、关键决策 |
| 4 | 关键 | 非常重要 | 敏感凭证、重要目标 |
| 5 | 核心 | 最重要 | 身份信息、核心目标 |

---

## 模块接口

```python
class MemoryWeight:
    # 权重常量
    LOW = 1
    MEDIUM = 2
    HIGH = 3
    CRITICAL = 4
    CORE = 5

    def __init__(self) -> None

    def set_weight(self, entry_id: str, weight: int) -> bool
    # 设置记忆权重 (1-5)

    def get_weight(self, entry_id: str) -> int
    # 获取记忆权重，默认返回 2 (MEDIUM)

    def adjust_weight(self, entry_id: str, delta: int) -> int
    # 调整权重值 (+1/-1)

    def rank_results(self, results: list[dict], boost_recent: bool = True) -> list[dict]
    # 对检索结果按权重排序，可选提升近期记忆
```

---

## 使用方式

### 保存时设置权重

```python
from core.ltm import LTMManager
from core.weight import MemoryWeight

ltm = LTMManager(memory_dir)
weight = MemoryWeight()

# 保存高权重记忆
entry = ltm.save(
    content="用户偏好简洁的代码风格",
    category="preference",
    tags=["偏好", "代码风格"]
)
weight.set_weight(entry.id, MemoryWeight.HIGH)
```

### 检索时按权重排序

```python
# 关键词检索
results = ltm.search("代码风格")

# 按权重排序（近期记忆加权）
ranked = weight.rank_results(results, boost_recent=True)

# 结果按 [高权重, 近期] 优先排序
for r in ranked:
    print(f"[权重:{r['weight']}] {r['content']}")
```

### 手动调整权重

```python
# 用户标记为重要
weight.adjust_weight("mem_001", +1)  # 从 2 升到 3

# 用户认为不重要
weight.adjust_weight("mem_002", -1)  # 从 2 降到 1
```

---

## 自动权重建议

系统可以根据内容类型自动建议权重：

```python
def auto_suggest_weight(content: str, category: str) -> int:
    # 凭证类 → 关键
    if category == "credential":
        return MemoryWeight.CRITICAL
    
    # 偏好/决策 → 高
    if category in ["preference", "decision"]:
        return MemoryWeight.HIGH
    
    # 项目信息 → 中
    if category == "project":
        return MemoryWeight.MEDIUM
    
    # 默认
    return MemoryWeight.LOW
```

---

## 数据存储

权重信息存储在记忆文件的元数据中：

```yaml
- id: mem_001
  content: "用户喜欢简洁的代码风格"
  weight: 3  # HIGH
  category: preference
  created: 2026-03-17
```

---

*AI Memory System v1.1 | Generated by WorkBuddy | 2026-03-17*
